"""empty message

Revision ID: 094ee7267baf
Revises: c3d3f1d0f4a5
Create Date: 2023-08-28 12:52:58.146676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094ee7267baf'
down_revision = 'c3d3f1d0f4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
